[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000

[[inputs.mqtt_consumer]]
  servers = ["tcp://localhost:1883"]
  
  topics = [
    "sensors/+/temperature",
    "sensors/+/humidity",
    "sensors/+/co2",
    "sensors/+/voc"
  ]
  
  data_format = "json"

[[outputs.influxdb_v2]]
  urls = ["http://localhost:8086"]
  
  token = "ypQm_4mBScNSent3AND_oxK75S0LTsPvi5CbWPPaeFAcpPuWFBRsl2UUf9KcCKPHLyEUzIG0JXme97sTTEkNug=="
  organization = "etsisi"
  bucket = "waterdrop"

[[inputs.procstat]]
  pattern = "(mosquitto|influxd|telegraf|uvicorn|prox2mqtt|haproxy)"
