# --- CONFIGURACIÓN GLOBAL ---
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000

# --- INPUT: LEER DE MOSQUITTO ---
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  
  # A qué topics quieres suscribirte (el # significa "todo lo que esté dentro de sensores")
  topics = [
    "sensores/#"
  ]
  
  # Formato en el que envías los datos (JSON es lo más recomendable)
  data_format = "json"

# --- OUTPUT: ESCRIBIR EN INFLUXDB V2 ---
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  
  # Estos datos los obtendrás en el paso 4
  token = "TU_TOKEN_DE_INFLUXDB_AQUI"
  organization = "mi_organizacion"
  bucket = "sensores_bucket"
