[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["http://localhost:8086"]
  token = "IBat9xGTwamnLKMwb_YXTImjece1BAQ_pykx8fIBSZrTsvnomdtLzKG8Gnel-eKG1rVUiFXbMUIV71NcrCdgJw=="
  organization = "etsisi"
  bucket = "sensors"

[[inputs.mqtt_consumer]]
  servers = ["tcp://localhost:1883"]
  topics = [
    "sensors/+/temperature",
    "sensors/+/humidity",
    "sensors/+/co2",
    "sensors/+/voc"
  ]
  data_format = "json"
